# Generated by Django 5.0.14 on 2026-03-15 18:49

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(default=core.models._uuid, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=core.models._uuid, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(default=core.models._uuid, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(default=core.models._uuid, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('ai_tags', models.JSONField(blank=True, default=list)),
                ('ai_persona', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_product_fit', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_urgency', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('ai_tagged_at', models.DateTimeField(blank=True, null=True)),
                ('ai_tag_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_suggested_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('ai_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.CharField(default=core.models._uuid, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.person')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.CharField(default=core.models._uuid, max_length=36, primary_key=True, serialize=False)),
                ('stage', models.CharField(default='New Lead', max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(blank=True, default='', max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('event_count', models.IntegerField(default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_sources', to='core.person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.source')),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='core_person_email_9161a8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['score'], name='core_person_score_038ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['ai_tag_status'], name='core_person_ai_tag__951a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['source'], name='core_person_source_c6fc65_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage'], name='core_lead_stage_01080b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('person', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='referralsource',
            unique_together={('person', 'source')},
        ),
    ]
