# Generated by Django 5.0.14 on 2026-03-15 20:20

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_product_source_person_action_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=core.models._uuid, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('company_size', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.CharField(blank=True, max_length=500, null=True)),
                ('source_app', models.CharField(blank=True, max_length=100, null=True)),
                ('source_product', models.CharField(blank=True, max_length=255, null=True)),
                ('trigger', models.CharField(blank=True, max_length=100, null=True)),
                ('score_hints', models.JSONField(blank=True, default=dict)),
                ('raw_context', models.TextField(blank=True, default='')),
                ('contact_type', models.CharField(blank=True, choices=[('', 'Unclassified'), ('person', 'Person'), ('business', 'Business')], default='', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('classified', 'Classified'), ('converted', 'Converted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_contacts', to='core.business')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_contacts', to='core.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_contac_status_f2a872_idx'), models.Index(fields=['contact_type'], name='core_contac_contact_340f61_idx'), models.Index(fields=['source_app'], name='core_contac_source__38bbb3_idx'), models.Index(fields=['source_product'], name='core_contac_source__653475_idx')],
            },
        ),
    ]
